---
deployment:
      tasks:
        - export DEPLOYPATH=/home/gitdemocaddickno/testrepo
        - /bin cp /stylesheets/* $DEPLOYPATH
        #- /bin/cp readme.txt $DEPLOYPATH #Copy specific file to destination from root
        #- /bin/cp /<sub_folder>/<file_name> $DEPLOYPATH #copy specific file from source sub folder
        #- /bin cp * $DEPLOYPATH #copy all from root 
        #- /bin cp /<sub_folder>/* $DEPLOYPATH #copy all from sub folder root